// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shfhtyrwyggfzgajzvex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoZmh0eXJ3eWdnZnpnYWp6dmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMTA1NDcsImV4cCI6MjA1NjY4NjU0N30.WU7jbBiDxlDR3TcOH-sgxMSGSV__s8LuC4CYy2qB11E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);